<?php

namespace Drupal\playground_form\Form;

use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\AppendCommand;
use Drupal\user\RegisterForm;
use Drupal\Core\Form\FormStateInterface;

class NewRegisterForm extends RegisterForm {

  protected function actions(array $form, FormStateInterface $form_state) {
    $element = parent::actions($form, $form_state);
    $element['submit']['#value'] = 'Submit';
    return $element;
  }

  public function form(array $form, FormStateInterface $form_state) {
    // Start with the default user account fields.
    $form = parent::form($form, $form_state);

    $form['field_address']['widget'][0]['value']['#placeholder'] = 'Please enter your address.';
    $form['field_address']['widget'][0]['value']['#description'] = '';
    //    $form['field_address']['widget'][0]['value'] ['#ajax'] = [
    //      'callback' => [$this, 'countCharactersAjaxCallback'],
    //      'disable-refocus' => FALSE,
    //      'event' => 'change',
    //      'progress' => [
    //        'type' => 'throbber',
    //        'message' => $this->t('Calculating entry...'),
    //      ],
    //    ];

    $form['field_about_me']['widget'][0]['value']['#description'] = '';
    $form['field_about_me']['widget'][0]['value']['#maxlength'] = 300;
    $form['field_about_me']['widget'][0]['value']['#ajax'] = [
      'callback' => [$this, 'countCharactersAjaxCallback'],
      'disable-refocus' => TRUE,
      'event' => 'change',
      'progress' => [
        'type' => 'throbber',
        'message' => $this->t('Calculating entry...'),
      ],
    ];

    $form['field_postcode']['widget'][0]['value']['#maxlength'] = 4;
    return $form;
  }

  public function save(array $form, FormStateInterface $form_state) {
    parent::save($form, $form_state); // TODO: Change the autogenerated stub
  }

  public function submitForm(array &$form, FormStateInterface $form_state) {
    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  public function countCharactersAjaxCallback(array &$form, FormStateInterface $form_state) {
    $response = new AjaxResponse();
    $size = strlen($form_state->getValue('field_about_me')[0]['value']);
    $max_size = $form['field_about_me']['widget'][0]['value']['#maxlength'];
    $text = '%d out of %d characters used.';
    $response->addCommand(new AppendCommand('.form-item-field-about-me-0-value ', '<label>' . sprintf($text, $size, $max_size) . '</label>'));
    return $response;
  }

  public function validateForm(array &$form, FormStateInterface $form_state) {
    return parent::validateForm($form, $form_state); // TODO: Change the autogenerated stub
  }

}
